### ISSUE TITLE
It is a nice work which enlightens me a lot! But I have some question want to ask!

### ISSUE THREAD

**Issue by czjghost** [gydpku/OCM#1]
By the way, do you have the implementation about reduced resnet18？Or just changing the FC will work on reduced resnet18? Because I find the MIR, ER, GSS, ASER, SCR are all experiment on reduced resnet18. I would be appreciated if you could help me. Thank you!

**Comment by czjghost** [comment]
By the way, are you sure you code has debugged successfully when it runs？I found I run it simclr_aug report "RuntimeError: adaptive_avg_pool2d: output_size must be 2".

**Comment by gydpku** [comment]
> By the way, are you sure you code has debugged successfully when it runs？I found I run it simclr_aug report "RuntimeError: adaptive_avg_pool2d: output_size must be 2".

You should use torch1.4 . The later version doesn't support this operation.

**Comment by czjghost** [comment]
thanks, I find if the version of torch is higher 1.8, just change following:
Before: resize_crop = TL.RandomResizedCropLayer(scale=resize_scale, size=[32, 32, 3]).cuda()
After: resize_crop = TL.RandomResizedCropLayer(scale=resize_scale, size=[32, 32]).cuda()

could run! maybe it can help others

**Comment by gydpku** [comment]
> By the way, do you have the implementation about reduced resnet18？ Or just changing the FC will work on reduced resnet18? Because I find the MIR, ER, GSS, ASER, and SCR are all experiments on reduced resnet18. I would be appreciated it if you could help me. Thank you!
You can just change the ResNet architecture (Resnet18.py) into what you want.

**Comment by czjghost** [comment]
> > By the way, do you have the implementation about reduced resnet18？ Or just changing the FC will work on reduced resnet18? Because I find the MIR, ER, GSS, ASER, and SCR are all experiments on reduced resnet18. I would be appreciated it if you could help me. Thank you!
> You can just change the ResNet architecture (Resnet18.py) into what you want.
> 
> 

okay，thanks

**Comment by czjghost** [comment]
> > By the way, do you have the implementation about reduced resnet18？ Or just changing the FC will work on reduced resnet18? Because I find the MIR, ER, GSS, ASER, and SCR are all experiments on reduced resnet18. I would be appreciated it if you could help me. Thank you!
> > You can just change the ResNet architecture (Resnet18.py) into what you want.

Excuse me，coud I set "with torch.no_grad()" for Previous_model? As I see in your paper, I think it just a new pose to distill old knowledge? So old model may not need grad?

**Comment by gydpku** [comment]
> > > By the way, do you have the implementation about reduced resnet18？ Or just changing the FC will work on reduced resnet18? Because I find the MIR, ER, GSS, ASER, and SCR are all experiments on reduced resnet18. I would be appreciated it if you could help me. Thank you!
> > > You can just change the ResNet architecture (Resnet18.py) into what you want.
> 
> Excuse me，coud I set "with torch.no_grad()" for Previous_model? As I see in your paper, I think it just a new pose to distill old knowledge? So old model may not need grad?

No problem.

**Comment by czjghost** [comment]
> > > > By the way, do you have the implementation about reduced resnet18？ Or just changing the FC will work on reduced resnet18? Because I find the MIR, ER, GSS, ASER, and SCR are all experiments on reduced resnet18. I would be appreciated it if you could help me. Thank you!
> > > > You can just change the ResNet architecture (Resnet18.py) into what you want.
> > 
> > Excuse me，coud I set "with torch.no_grad()" for Previous_model? As I see in your paper, I think it just a new pose to distill old knowledge? So old model may not need grad?
> 
> No problem.

thank you very much
